# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20161014_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='ability',
            new_name='hability',
        ),
    ]
